# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\\main\\python\\ui\\main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1155, 675)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1155, 675))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 2))
        self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.upperbars = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperbars.sizePolicy().hasHeightForWidth())
        self.upperbars.setSizePolicy(sizePolicy)
        self.upperbars.setMinimumSize(QtCore.QSize(1000, 0))
        self.upperbars.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.upperbars.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upperbars.setObjectName("upperbars")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.upperbars)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titlebar = QtWidgets.QFrame(self.upperbars)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titlebar.sizePolicy().hasHeightForWidth())
        self.titlebar.setSizePolicy(sizePolicy)
        self.titlebar.setMinimumSize(QtCore.QSize(0, 30))
        self.titlebar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.titlebar.setAutoFillBackground(False)
        self.titlebar.setStyleSheet("border: none;background-color: rgb(16, 23, 30);border-color:none;border-radius: none;")
        self.titlebar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titlebar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.titlebar.setLineWidth(0)
        self.titlebar.setObjectName("titlebar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.titlebar)
        self.horizontalLayout_3.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.titlebar)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.titlebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(200, 30))
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Cute Zealand")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.minimizebutton = QtWidgets.QPushButton(self.titlebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizebutton.sizePolicy().hasHeightForWidth())
        self.minimizebutton.setSizePolicy(sizePolicy)
        self.minimizebutton.setMinimumSize(QtCore.QSize(47, 30))
        self.minimizebutton.setMaximumSize(QtCore.QSize(47, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.minimizebutton.setFont(font)
        self.minimizebutton.setStyleSheet(":hover{background-color: rgb(49, 71, 93);border-color: none;border-radius: 0px;border:1px }")
        self.minimizebutton.setFlat(False)
        self.minimizebutton.setObjectName("minimizebutton")
        self.horizontalLayout_3.addWidget(self.minimizebutton)
        self.resizebutton = QtWidgets.QPushButton(self.titlebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resizebutton.sizePolicy().hasHeightForWidth())
        self.resizebutton.setSizePolicy(sizePolicy)
        self.resizebutton.setMinimumSize(QtCore.QSize(47, 30))
        self.resizebutton.setMaximumSize(QtCore.QSize(47, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.resizebutton.setFont(font)
        self.resizebutton.setStyleSheet(":hover{background-color: rgb(49, 71, 93);border-color: none;border-radius: 0px;border:1px }")
        self.resizebutton.setFlat(False)
        self.resizebutton.setObjectName("resizebutton")
        self.horizontalLayout_3.addWidget(self.resizebutton)
        self.closebutton = QtWidgets.QPushButton(self.titlebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closebutton.sizePolicy().hasHeightForWidth())
        self.closebutton.setSizePolicy(sizePolicy)
        self.closebutton.setMinimumSize(QtCore.QSize(47, 30))
        self.closebutton.setMaximumSize(QtCore.QSize(47, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        self.closebutton.setFont(font)
        self.closebutton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.closebutton.setStyleSheet(":hover{background-color: rgb(218, 16, 32);border-color: none;border-radius: 0px;border:1px }")
        self.closebutton.setFlat(True)
        self.closebutton.setObjectName("closebutton")
        self.horizontalLayout_3.addWidget(self.closebutton)
        self.verticalLayout_2.addWidget(self.titlebar)
        self.frame_3 = QtWidgets.QFrame(self.upperbars)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setStyleSheet("border: 0;\n"
"background-color: rgb(28, 41, 54);border-radius:none;border-color:none")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.File = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.File.sizePolicy().hasHeightForWidth())
        self.File.setSizePolicy(sizePolicy)
        self.File.setMinimumSize(QtCore.QSize(100, 30))
        self.File.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.File.setStyleSheet(":hover{background-color: rgb(49, 71, 93);border-color: none;border-radius: 0px;border:1px }")
        self.File.setAutoRepeatInterval(100)
        self.File.setFlat(True)
        self.File.setObjectName("File")
        self.horizontalLayout_2.addWidget(self.File)
        self.settingsbutton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsbutton.sizePolicy().hasHeightForWidth())
        self.settingsbutton.setSizePolicy(sizePolicy)
        self.settingsbutton.setMinimumSize(QtCore.QSize(100, 30))
        self.settingsbutton.setStyleSheet(":hover{background-color: rgb(49, 71, 93);border-color: none;border-radius: 0px;border:1px }")
        self.settingsbutton.setFlat(True)
        self.settingsbutton.setObjectName("settingsbutton")
        self.horizontalLayout_2.addWidget(self.settingsbutton)
        spacerItem1 = QtWidgets.QSpacerItem(1055, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.line = QtWidgets.QFrame(self.upperbars)
        self.line.setMinimumSize(QtCore.QSize(1, 0))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout_4.addWidget(self.upperbars)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(1155, 30))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_5.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 30))
        self.label_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_5.addWidget(self.checkBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.leftarrow = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftarrow.sizePolicy().hasHeightForWidth())
        self.leftarrow.setSizePolicy(sizePolicy)
        self.leftarrow.setMinimumSize(QtCore.QSize(31, 31))
        self.leftarrow.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.leftarrow.setFont(font)
        self.leftarrow.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"border-color: rgb(25, 35, 45);")
        self.leftarrow.setObjectName("leftarrow")
        self.horizontalLayout_5.addWidget(self.leftarrow)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(90, 21))
        self.label_3.setMaximumSize(QtCore.QSize(90, 21))
        font = QtGui.QFont()
        font.setFamily("Cute Zealand")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.rightarrow = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightarrow.sizePolicy().hasHeightForWidth())
        self.rightarrow.setSizePolicy(sizePolicy)
        self.rightarrow.setMinimumSize(QtCore.QSize(31, 31))
        self.rightarrow.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rightarrow.setFont(font)
        self.rightarrow.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"border-color: rgb(25, 35, 45);")
        self.rightarrow.setObjectName("rightarrow")
        self.horizontalLayout_5.addWidget(self.rightarrow)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.inputs = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputs.sizePolicy().hasHeightForWidth())
        self.inputs.setSizePolicy(sizePolicy)
        self.inputs.setMinimumSize(QtCore.QSize(1000, 53))
        self.inputs.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.inputs.setFrameShadow(QtWidgets.QFrame.Raised)
        self.inputs.setLineWidth(0)
        self.inputs.setObjectName("inputs")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.inputs)
        self.horizontalLayout_6.setContentsMargins(20, 5, 20, 10)
        self.horizontalLayout_6.setSpacing(15)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.clientlabel = QtWidgets.QLabel(self.inputs)
        font = QtGui.QFont()
        font.setFamily("Cute Zealand")
        font.setPointSize(20)
        self.clientlabel.setFont(font)
        self.clientlabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clientlabel.setStyleSheet("background-color:yellow,\n"
":hover{border-color: rgb(255, 255, 0);border:5px;border-radius:5px;\n"
"background-color: rgb(28, 41, 54)}\n"
"")
        self.clientlabel.setObjectName("clientlabel")
        self.horizontalLayout_6.addWidget(self.clientlabel)
        self.lineEdit = QtWidgets.QLineEdit(self.inputs)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 51))
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 51))
        font = QtGui.QFont()
        font.setFamily("Cute Zealand")
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setToolTip("")
        self.lineEdit.setPlaceholderText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit)
        self.yearline = QtWidgets.QLineEdit(self.inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yearline.sizePolicy().hasHeightForWidth())
        self.yearline.setSizePolicy(sizePolicy)
        self.yearline.setMinimumSize(QtCore.QSize(155, 51))
        self.yearline.setMaximumSize(QtCore.QSize(155, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        self.yearline.setFont(font)
        self.yearline.setStyleSheet("")
        self.yearline.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.yearline.setAlignment(QtCore.Qt.AlignCenter)
        self.yearline.setObjectName("yearline")
        self.horizontalLayout_6.addWidget(self.yearline)
        self.verticalLayout_4.addWidget(self.inputs)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(20, 5, 20, 11)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.backbutton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backbutton.sizePolicy().hasHeightForWidth())
        self.backbutton.setSizePolicy(sizePolicy)
        self.backbutton.setMinimumSize(QtCore.QSize(31, 31))
        self.backbutton.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.backbutton.setFont(font)
        self.backbutton.setStyleSheet("background-color: rgb(28, 41, 54);")
        self.backbutton.setObjectName("backbutton")
        self.horizontalLayout_4.addWidget(self.backbutton)
        self.forwardbutton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forwardbutton.sizePolicy().hasHeightForWidth())
        self.forwardbutton.setSizePolicy(sizePolicy)
        self.forwardbutton.setMinimumSize(QtCore.QSize(31, 31))
        self.forwardbutton.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.forwardbutton.setFont(font)
        self.forwardbutton.setStyleSheet("background-color: rgb(28, 41, 54);")
        self.forwardbutton.setObjectName("forwardbutton")
        self.horizontalLayout_4.addWidget(self.forwardbutton)
        self.upper = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upper.sizePolicy().hasHeightForWidth())
        self.upper.setSizePolicy(sizePolicy)
        self.upper.setMinimumSize(QtCore.QSize(31, 31))
        self.upper.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.upper.setFont(font)
        self.upper.setStyleSheet("background-color: rgb(28, 41, 54);")
        self.upper.setObjectName("upper")
        self.horizontalLayout_4.addWidget(self.upper)
        self.addressbar = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addressbar.sizePolicy().hasHeightForWidth())
        self.addressbar.setSizePolicy(sizePolicy)
        self.addressbar.setMinimumSize(QtCore.QSize(500, 31))
        self.addressbar.setObjectName("addressbar")
        self.horizontalLayout_4.addWidget(self.addressbar)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout.setContentsMargins(20, 10, 20, 10)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.infoframe = QtWidgets.QFrame(self.frame_5)
        self.infoframe.setMinimumSize(QtCore.QSize(20, 0))
        self.infoframe.setMaximumSize(QtCore.QSize(280, 16777215))
        self.infoframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.infoframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoframe.setObjectName("infoframe")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.infoframe)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.infoarea = QtWidgets.QScrollArea(self.infoframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoarea.sizePolicy().hasHeightForWidth())
        self.infoarea.setSizePolicy(sizePolicy)
        self.infoarea.setMinimumSize(QtCore.QSize(260, 0))
        self.infoarea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.infoarea.setBaseSize(QtCore.QSize(260, 0))
        self.infoarea.setStyleSheet("border-radius:0px")
        self.infoarea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.infoarea.setWidgetResizable(True)
        self.infoarea.setObjectName("infoarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 260, 424))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.infoarea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_7.addWidget(self.infoarea)
        self.hide_unhide_info = QtWidgets.QPushButton(self.infoframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hide_unhide_info.sizePolicy().hasHeightForWidth())
        self.hide_unhide_info.setSizePolicy(sizePolicy)
        self.hide_unhide_info.setMinimumSize(QtCore.QSize(20, 412))
        self.hide_unhide_info.setMaximumSize(QtCore.QSize(20, 16777215))
        self.hide_unhide_info.setStyleSheet("border-radius:0px")
        self.hide_unhide_info.setObjectName("hide_unhide_info")
        self.horizontalLayout_7.addWidget(self.hide_unhide_info)
        self.horizontalLayout.addWidget(self.infoframe)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_5)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.treeView = QtWidgets.QTreeView(self.tab)
        self.treeView.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setMinimumSize(QtCore.QSize(0, 0))
        self.treeView.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.treeView.setFont(font)
        self.treeView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.treeView.setStyleSheet("border-radius:0px")
        self.treeView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeView.setLineWidth(0)
        self.treeView.setProperty("showDropIndicator", False)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeView.setItemsExpandable(False)
        self.treeView.setExpandsOnDoubleClick(False)
        self.treeView.setObjectName("treeView")
        self.horizontalLayout_8.addWidget(self.treeView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_4.addWidget(self.frame_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.minimizebutton, self.closebutton)
        MainWindow.setTabOrder(self.closebutton, self.File)
        MainWindow.setTabOrder(self.File, self.settingsbutton)
        MainWindow.setTabOrder(self.settingsbutton, self.leftarrow)
        MainWindow.setTabOrder(self.leftarrow, self.rightarrow)
        MainWindow.setTabOrder(self.rightarrow, self.yearline)
        MainWindow.setTabOrder(self.yearline, self.backbutton)
        MainWindow.setTabOrder(self.backbutton, self.forwardbutton)
        MainWindow.setTabOrder(self.forwardbutton, self.addressbar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Client File Browser v2.0"))
        self.minimizebutton.setText(_translate("MainWindow", "—"))
        self.resizebutton.setText(_translate("MainWindow", "🗖"))
        self.closebutton.setText(_translate("MainWindow", "×"))
        self.File.setText(_translate("MainWindow", "File"))
        self.settingsbutton.setText(_translate("MainWindow", "Settings"))
        self.label_2.setText(_translate("MainWindow", "CLIENT NAME"))
        self.checkBox.setText(_translate("MainWindow", "Jump to Workpaper Folder"))
        self.leftarrow.setText(_translate("MainWindow", "⯇"))
        self.label_3.setText(_translate("MainWindow", "TAX YEAR"))
        self.rightarrow.setText(_translate("MainWindow", "⯈"))
        self.clientlabel.setText(_translate("MainWindow", "Select a client..."))
        self.backbutton.setText(_translate("MainWindow", "🡄"))
        self.forwardbutton.setText(_translate("MainWindow", "🡆"))
        self.upper.setText(_translate("MainWindow", "🡅"))
        self.hide_unhide_info.setText(_translate("MainWindow", "⯇"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "58 Paerangi Consolidated Group"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ma. Ferlline Kay Cayabyab Magcalas"))

import qrc_rc
